//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Unos_sporta;
namespace SmartFitness
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnik()
        {
            this.uceniks = new HashSet<ucenik>();
        }
    
        public int id_korisnika { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string zvanje { get; set; }
        public int godina_staza { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ucenik> uceniks { get; set; }

        public static bool ProvjeraPrijave(string korisnickoIme, string lozinka)
        {

            using (var db = new SmartFitnessEntities())
            {
                var korisnik = db.korisniks.FirstOrDefault(a =>
                    a.korisnicko_ime == korisnickoIme && a.lozinka == lozinka);
                if (korisnik != null)
                {
                    return true;
                }
                return false;
            }
        }
    }
}
