//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;

namespace SmartFitness
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class natjecanje_ucenik
    {
        public int natjecanje_ucenik__id { get; set; }
        public int natjecanje_id_natjecanja { get; set; }
        public int ucenik_id_ucenika { get; set; }
        public Nullable<int> godina_sudjelovanja { get; set; }

        public virtual natjecanje natjecanje { get; set; }
        public virtual ucenik ucenik { get; set; }

        public static natjecanje_ucenik DohvatiNatjecanjeUcenika(int ucenikId, int natjecanjeId)
        {
            natjecanje_ucenik natjecanjeUcenika = null;
            using (var db = new SmartFitnessEntities())
            {
                natjecanjeUcenika = db.natjecanje_ucenik.FirstOrDefault(nu =>
                    nu.ucenik_id_ucenika == ucenikId && nu.natjecanje_id_natjecanja == natjecanjeId);
            }

            return natjecanjeUcenika;
        }

        public static void DodajUcenikaNaNatjecanje(int ucenikId, int godina, int natjecanjeId)
        {
            using (var db = new SmartFitnessEntities())
            {
                natjecanje_ucenik natjecanjeUcenik = new natjecanje_ucenik
                {
                    ucenik_id_ucenika = ucenikId,
                    godina_sudjelovanja = godina,
                    natjecanje_id_natjecanja = natjecanjeId

                };
                db.natjecanje_ucenik.Add(natjecanjeUcenik);
                db.SaveChanges();
            }
        }

        public static ArrayList DohvatiNatjecanjaUcenika(int ucenikId)
        {
            ArrayList listaNatjecanjaUcenika = new ArrayList();
            using (var db = new SmartFitnessEntities())
            {
                var lista =
                    (from n in db.natjecanjes
                        join nu in db.natjecanje_ucenik on n.id_natjecanja equals nu.natjecanje_id_natjecanja
                        join u in db.uceniks on nu.ucenik_id_ucenika equals u.id_ucenika
                        join s in db.sports on n.id_sporta equals s.id_sporta
                        where u.id_ucenika == ucenikId
                        select new
                        {
                            Sport = s.naziv,
                            Razina = n.razina_natjecanja,
                            Mjesto = n.mjesto_odrzavanja,
                            Datum = n.datum_vrijeme,
                            Opis = n.opis,
                            natjecanjeId = nu.natjecanje_ucenik__id
                        }).ToList();
                listaNatjecanjaUcenika.AddRange(lista);
            }

            return listaNatjecanjaUcenika;
        }

        public static natjecanje_ucenik DohvatiNatjecanjePoIdu(int natjecanjeId)
        {
            natjecanje_ucenik natjecanjeUcenika = null;
            using (var db = new SmartFitnessEntities())
            {
                natjecanjeUcenika = db.natjecanje_ucenik.FirstOrDefault(x => x.natjecanje_ucenik__id == natjecanjeId);
            }
            return natjecanjeUcenika;
        }

        public static void ObrisiNatjecanjeUcenika(natjecanje_ucenik natjecanjeUcenika)
        {
            using (var db = new SmartFitnessEntities())
            {
                db.natjecanje_ucenik.Attach(natjecanjeUcenika);
                db.natjecanje_ucenik.Remove(natjecanjeUcenika);
                db.SaveChanges();
            }
        }
    }
}
