//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartFitnessEntities : DbContext
    {
        public SmartFitnessEntities()
            : base("name=SmartFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<natjecanje> natjecanjes { get; set; }
        public virtual DbSet<natjecanje_ucenik> natjecanje_ucenik { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<sport_ucenik> sport_ucenik { get; set; }
        public virtual DbSet<ucenik> uceniks { get; set; }
        public virtual DbSet<vjezba> vjezbas { get; set; }
        public virtual DbSet<vjezba_ucenik> vjezba_ucenik { get; set; }
    }
}
