//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Linq;

namespace SmartFitness
{
    using System;
    using System.Collections.Generic;
    
    public partial class sport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sport()
        {
            this.natjecanjes = new HashSet<natjecanje>();
            this.sport_ucenik = new HashSet<sport_ucenik>();
        }
    
        public int id_sporta { get; set; }
        public string naziv { get; set; }
        public string disciplina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<natjecanje> natjecanjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sport_ucenik> sport_ucenik { get; set; }

        public static BindingList<sport> DohvatiSportove()
        {
            BindingList<sport> listaSportova = null;
            using (var db = new SmartFitnessEntities())
            {
                listaSportova = new BindingList<sport>(db.sports.ToList());
            }
            return listaSportova;
        }


        public static void DodavanjeSporta(string naziv,string disciplina)
        {
            using (var db = new SmartFitnessEntities())
            {
                sport sport = new sport
                {
                    naziv = naziv,
                    disciplina = disciplina,
                };
                db.sports.Add(sport);
                db.SaveChanges();
            }
        }
        public static void AzuriranjeSporta(string naziv, string disciplina,sport odabrani)
        {
            using (var db = new SmartFitnessEntities())
            {
                db.sports.Attach(odabrani);
                odabrani.naziv = naziv;
                odabrani.disciplina = disciplina;
                db.SaveChanges();
                
            }
        }
        public static void BrisanjeSporta(sport odabrani)
        {
            using (var db = new SmartFitnessEntities())
            {
                db.sports.Attach(odabrani);
                db.sports.Remove(odabrani);
                db.SaveChanges();

            }
        }



    }
}
