//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.ComponentModel;

namespace SmartFitness
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class sport_ucenik
    {
        public int id_ucenik_sport { get; set; }
        public int sport_id_sporta { get; set; }
        public int ucenik_id_ucenika { get; set; }
        public System.DateTime datum { get; set; }
        public int ocijena { get; set; }
        public string opis { get; set; }
    
        public virtual sport sport { get; set; }
        public virtual ucenik ucenik { get; set; }

        public static sport_ucenik DohvatiSportIOcijenuUcenika(ucenik ucenik, sport sport)
        {
            sport_ucenik sportIOcijena = null;
            using (var db = new SmartFitnessEntities())
            {
                sportIOcijena = db.sport_ucenik.FirstOrDefault(o =>
                    o.ucenik_id_ucenika == ucenik.id_ucenika &&
                    o.sport_id_sporta == sport.id_sporta);
            }
            return sportIOcijena;
        }

        public static sport_ucenik DohvatiSportIOcijenuUcenika(int vjezbaId)
        {
            sport_ucenik sportIOcijena = null;
            using (var db = new SmartFitnessEntities())
            {
                var rezultat = (from s1 in db.sport_ucenik
                    where s1.id_ucenik_sport == vjezbaId
                    select s1).SingleOrDefault();
            }
            return sportIOcijena;
        }

        public static void DodajOcijenuUceniku(int sportId, int ucenikId, DateTime datum, int ocijena, string opis)
        {
            using (var db = new SmartFitnessEntities())
            {
                var sport_ucenik = new sport_ucenik
                {
                    sport_id_sporta = sportId,
                    ucenik_id_ucenika = ucenikId,
                    datum = datum,
                    ocijena = ocijena,
                    opis = opis
                };
                db.sport_ucenik.Add(sport_ucenik);
                db.SaveChanges();
            }
        }

        public static void ObrisiOcijenuUcenika(sport_ucenik sportUcenika)
        {
            using (var db = new SmartFitnessEntities())
            {
                db.sport_ucenik.Attach(sportUcenika);
                db.sport_ucenik.Remove(sportUcenika);
                db.SaveChanges();
            }
        }

        public static void AzurirajOcijenuUcenika(sport_ucenik sportUcenika, DateTime datum, int ocijena, string opis)
        {
            using (var db = new SmartFitnessEntities())
            {
                sportUcenika.datum = datum;
                sportUcenika.ocijena = ocijena;
                sportUcenika.opis = opis;
                db.SaveChanges();
            }
        }
    }
}
