//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Natjecanje_ucenik
    {
        public int id_ucenik_natjecanje { get; set; }
        public int Natjecanjeid_natjecanja { get; set; }
        public int Ucenikid_ucenika { get; set; }
        public Nullable<int> godina_sudjelovanja { get; set; }
    
        public virtual Natjecanje Natjecanje { get; set; }
        public virtual Ucenik Ucenik { get; set; }
    }
}
