//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Natjecanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Natjecanje()
        {
            this.Natjecanje_ucenik = new HashSet<Natjecanje_ucenik>();
        }
    
        public int id_natjecanja { get; set; }
        public string opis { get; set; }
        public string razina_natjecanja { get; set; }
        public string mjesto_odrzavanja { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Natjecanje_ucenik> Natjecanje_ucenik { get; set; }
    }
}
