//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartFitnessEntities : DbContext
    {
        public SmartFitnessEntities()
            : base("name=SmartFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Natjecanje> Natjecanjes { get; set; }
        public virtual DbSet<Natjecanje_ucenik> Natjecanje_ucenik { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Sport_ucenik> Sport_ucenik { get; set; }
        public virtual DbSet<Statistika> Statistikas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ucenik> Uceniks { get; set; }
        public virtual DbSet<Vjezba> Vjezbas { get; set; }
        public virtual DbSet<Vjezba_ucenik> Vjezba_ucenik { get; set; }
    }
}
