//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport_ucenik
    {
        public int id_ucenik_sport { get; set; }
        public int Sportid_sporta { get; set; }
        public int Ucenikid_ucenika { get; set; }
        public System.DateTime datum { get; set; }
        public int ocijena { get; set; }
        public string opis { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual Ucenik Ucenik { get; set; }
    }
}
