//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vjezba_ucenik
    {
        public int id_ucenik_vjezba { get; set; }
        public int Vjezbaid_vjezbe { get; set; }
        public int Ucenikid_ucenika { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual Ucenik Ucenik { get; set; }
        public virtual Vjezba Vjezba { get; set; }
    }
}
