//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unos_sporta
{
    using System;
    using System.Collections.Generic;
    
    public partial class natjecanje_ucenik
    {
        public int natjecanje_ucenik__id { get; set; }
        public int natjecanje_id_natjecanja { get; set; }
        public int ucenik_id_ucenika { get; set; }
        public Nullable<int> godina_sudjelovanja { get; set; }
    
        public virtual natjecanje natjecanje { get; set; }
        public virtual ucenik ucenik { get; set; }
    }
}
