//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unos_sporta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartFitnessEntities1 : DbContext
    {
        public SmartFitnessEntities1()
            : base("name=SmartFitnessEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<natjecanje> natjecanje { get; set; }
        public virtual DbSet<natjecanje_ucenik> natjecanje_ucenik { get; set; }
        public virtual DbSet<sport> sport { get; set; }
        public virtual DbSet<sport_ucenik> sport_ucenik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ucenik> ucenik { get; set; }
        public virtual DbSet<vjezba> vjezba { get; set; }
        public virtual DbSet<vjezba_ucenik> vjezba_ucenik { get; set; }
    }
}
