//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unos_sporta
{
    using System;
    using System.Collections.Generic;
    
    public partial class sport_ucenik
    {
        public int id_ucenik_sport { get; set; }
        public int sport_id_sporta { get; set; }
        public int ucenik_id_ucenika { get; set; }
        public System.DateTime datum { get; set; }
        public int ocijena { get; set; }
        public string opis { get; set; }
    
        public virtual sport sport { get; set; }
        public virtual ucenik ucenik { get; set; }
    }
}
